server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka中的实例名
    #hostname: localhost
  client:
    register-with-eureka: false #不注册自己
    fetch-registry: false #不获取注册实例
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/

